### ISSUE TITLE
XML request and Response show in single line instead of showing proper XML.

### ISSUE THREAD

**Issue by matifniaz** [filiphric/cypress-plugin-api#100]
XML requests and Responses are displayed in a single line instead of displaying in proper XML.
![image](https://user-images.githubusercontent.com/40147842/210182483-fa5b7214-c6bd-4660-a5e8-7666968a4a16.png)
Kindly add support for displaying XML.

**Comment by filiphric** [comment]
Hey @matifniaz the plugin actually has support for xml, but it relies on server returning `text/xml` in response header from server. What kind of header does your response header have?

**Comment by matifniaz** [comment]
![image](https://user-images.githubusercontent.com/40147842/212062797-4f476748-f9b3-48aa-b423-6f2a573ec603.png)
we received **Content-Type: application/octet-stream**

**Comment by filiphric** [comment]
releasing fix for this in version 2.10.0

**Comment by matifniaz** [comment]
![image](https://user-images.githubusercontent.com/40147842/213332367-f492499e-1b91-41ac-914f-e56f48c2450f.png)
Still, it's now showing in showing proper XML.

**Comment by filiphric** [comment]
> ![image](https://user-images.githubusercontent.com/40147842/213332367-f492499e-1b91-41ac-914f-e56f48c2450f.png)
> 
> Still, it's now showing in showing proper XML.

The fix now checks whether the response is a valid xml. If it is it will treat it like one, otherwise it's formatted as plain text. 

From the screenshot, it seems that the string is not valid xml because it does not have a closing tag. Not sure there's anything I can do if the xml is not valid.
