### ISSUE TITLE
Base UI display with API URL .

### ISSUE THREAD

**Issue by matifniaz** [filiphric/cypress-plugin-api#101]
Base UI display with API URL.
**Cypress Config**
![image](https://user-images.githubusercontent.com/40147842/210182558-0c7d7624-a1b5-4750-b0a4-3cb12e56b91a.png)
**My Code**
![image](https://user-images.githubusercontent.com/40147842/210182615-b8576308-10db-42a9-a243-f531f6f99ea4.png)
**URL displaying on the browser.**
![image](https://user-images.githubusercontent.com/40147842/210182590-f83a2e86-cad5-44fa-88b6-d733e20e0db3.png)

**Comment by filiphric** [comment]
Hey! Thanks for the report! Just releasing a fix 👍

**Comment by matifniaz** [comment]
Thanks @filiphric , it's fixed in the updated version.2.9.1
