### ISSUE TITLE
When you use ` followRedirect: false` on a request, the plugin doesn't give you the request information properly. 

### ISSUE THREAD

**Issue by estefafdez** [filiphric/cypress-plugin-api#11]
Hey @filiphric! first of all, great work with this incredible plugin :) 

We have a few tests to try the redirection on our website. Something like: 

```
it(`[should be redirected from ${originUrl} with query params`, () => {
      cy.request({
        method: 'GET',
        url: originUrl,
        followRedirect: false,
      }).then(response => {
        expect(response.status).eq(301);
        expect(response.redirectedToUrl).eq(destinyUrl);
      });
    });
```

When we use `cy.request()` it works properly but when we updated the code and used your plugin, we got the following error: 

<img width="730" alt="image" src="https://user-images.githubusercontent.com/6990209/194834349-5fed8c7d-cd19-46b5-b9f7-932cef89f53c.png">

It works properly with other `cy.request` but those tests are the only ones with the property `followRedirect: false` added on the request. 

Could you please have a look? Let me know if there's anything else we could help you with :) 

Again, great work!

**Comment by filiphric** [comment]
thanks for the great catch @estefafdez! I just fixed this and added a test. let me know if it works on version 1.2.2

**Comment by estefafdez** [comment]
works perfectly! thanks for the quick fix! :)
