### ISSUE TITLE
cy.api is not a function

### ISSUE THREAD

**Issue by chelsea-designs** [filiphric/cypress-plugin-api#119]
Good Morning,

I've tried to add the plugin but I'm getting 'cy.api is not a function'.

Steps I've taken:

- I ran `npm i cypress-plugin-api` and I see "cypress-plugin-api" in my node_modules folder.
- I added `import 'cypress-plugin-api'` to cypress/support/e2e.ts file.
- I added `"cypress-plugin-api"` to types in tsconfig.json
- I've replaced my `cy.request` with `cy.api`.

![image](https://user-images.githubusercontent.com/94197734/235856194-df3b7888-8803-4a99-a8e9-4dacfb66d9d9.png)
vs
![image](https://user-images.githubusercontent.com/94197734/235856377-fff30170-28dd-4ad0-b051-74422a8ec121.png)

Any help gratefully received?

**Comment by filiphric** [comment]
this is strange. it seems like you have done everything right and yet cypress does not recognize the command, have you tried adding your own custom command to e2e.ts and see if it’s found by your test? I could imagine that the support file is somehow not being loaded, maybe check your cypress.config.ts file

**Comment by chelsea-designs** [comment]
Thanks for your reply. Yes you were right, the supportFile in cypress.config.ts was pointing to index.ts so I've added import 'cypress-plugin-api' to that file instead which worked. Thanks for your help :)
