### ISSUE TITLE
Modules not setup properly

### ISSUE THREAD

**Issue by iepoch** [filiphric/cypress-plugin-api#131]
## As is

When installing cypress-api-plugin using --save-dev or -D for npm.  Not all files are written causing issue with missing structure for one of the modules. 

## To be
 Modules -> tansformData.d.ts uses an import { RequestProps } from 'src/types' 
 More Modules are like this not just transformData.d.ts

![image](https://github.com/filiphric/cypress-plugin-api/assets/7504929/d871ddc1-ab46-4b2f-b9a6-bc8657afd026)

## Steps for work around

Change the   Modules -> tansformData.d.ts uses an import { RequestProps } from '../types' 
This will work until you update the package again if you update the package this will get overwritten

**Comment by iepoch** [comment]
@filiphric Just curious are you still able to maintain this utility?

**Comment by filiphric** [comment]
Hey Stacy, I have much less time to maintain, so I’ll appreciate the help, but I’ll make sure to catch up soon.
