### ISSUE TITLE
trigger to show/not show whole URL

### ISSUE THREAD

**Issue by dodosaurus** [filiphric/cypress-plugin-api#17]
Some projects use multiple URLs in their repo. It would be nice to have option to turn on/off displaying of full URL, not just an appendix like it is now (in URL box of the UI, see screenshot).

![image](https://user-images.githubusercontent.com/28686994/195359725-e8d68a34-68da-472c-8a86-200b5c3d0a07.png)

**Comment by filiphric** [comment]
I’m thinking adding the whole URL including the baseUrl to the URL part
