### ISSUE TITLE
Interactive response body

### ISSUE THREAD

**Issue by AussieFlem** [filiphric/cypress-plugin-api#19]
For assessing the response payloads, it would be awesome if the JSON was interactive - particularly the ability to collapse sections and navigate the document as you would in an IDE.

**Comment by filiphric** [comment]
this is an awesome idea 👍 I was thinking we could maybe even add the ability to copy json path to a given key

**Comment by AussieFlem** [comment]
Search or filter for a node would be good too. We’ve got some pretty big response payload so quickly zeroing I’m on the one prop you’re looking for would be handy.

**Comment by filiphric** [comment]
JSON folding will be in next release. Copying JSON path and search are not part of this release. I’ll think of a way of implementing it in the future.

**Comment by AussieFlem** [comment]
Amazing @filiphric - great work!
