### ISSUE TITLE
Add the ability to hide the authorization

### ISSUE THREAD

**Issue by wlsf82** [filiphric/cypress-plugin-api#29]
When running API tests with the `cypress-plugin-api`, if authorization is needed (where it would have an API key, for example), such info is displayed in the Headers section.

For security reasons, it'd be nice to have the ability to hide such information.

**Comment by filiphric** [comment]
Had this in the back of my mind, since Gleb’s plugin has this. I’ll make sure to include this with one of the upcoming releases 👍

**Comment by wlsf82** [comment]
It'd be nice if it could be shown like this.

<img width="914" alt="Screenshot 2022-10-30 at 17 48 34" src="https://user-images.githubusercontent.com/2768415/198890822-fef1ba69-9c5e-47fe-b8ed-4974c5958570.png">

**Comment by filiphric** [comment]
What would you like to see happen when you click on "copy to clipboard" button? should it copy anonymized properties or the once that were sent?

**Comment by filiphric** [comment]
Well that was fun 🙁 Thanks for the feature request, just merged it into production 👍

**Comment by wlsf82** [comment]
> What would you like to see happen when you click on "copy to clipboard" button? should it copy anonymized properties or the once that were sent?

I think the non-anonymized properties.

**Comment by wlsf82** [comment]
Hey @filiphric, what if the authorization uses an uppercase A?

I.e., `Authorization` instead of `authorization`?

I've just upgraded to v1.7.0, and the API I'm interacting with seems only to Accept `Authorization`; in this case, the API key is still not hidden.

Could that be addressed, too, please?

**Comment by wlsf82** [comment]
Also, it would be nice if one could add the `{ env: { hideCredentials: true } }` to a whole `describe` or `context` block instead of individual `it` statements.

**Comment by filiphric** [comment]
> Also, it would be nice if one could add the `{ env: { hideCredentials: true } }` to a whole `describe` or `context` block instead of individual `it` statements.

you can, I even have tests written with `describe()`. or you can add it to `cypress.config.{js,ts}` file

**Comment by filiphric** [comment]
> Hey @filiphric, what if the authorization uses an uppercase A?
> 
> I.e., `Authorization` instead of `authorization`?
> 
> I've just upgraded to v1.7.0, and the API I'm interacting with seems only to Accept `Authorization`; in this case, the API key is still not hidden.
> 
> Could that be addressed, too, please?

this is a bug, I’ll make an issue and fix it

**Comment by wlsf82** [comment]
Also, please have a look at this comment https://github.com/filiphric/cypress-plugin-api/pull/30/files#r1008949489.
