### ISSUE TITLE
line numbers

### ISSUE THREAD

**Issue by filiphric** [filiphric/cypress-plugin-api#38]
add line numbers to every data block

**Comment by lucasdonato** [comment]
When we select the body, the line number is also being copied. Is there any way to copy without the number of lines?

![image](https://user-images.githubusercontent.com/12953400/200177867-4205194a-705e-48cb-8692-7a57e50489a7.png)

**Comment by filiphric** [comment]
Hmmm didn't realize this. I'll take a look into it

**Comment by filiphric** [comment]
made an issue #47 it’s actually a super easy fix, so release is coming in a second
