### ISSUE TITLE
null before API URL on verb section

### ISSUE THREAD

**Issue by wlsf82** [filiphric/cypress-plugin-api#40]
I've upgraded cypress-plugin-api from v1.7.1 to v2.1.0, using `npm i cypress-plugin-api@latest -D`, and now there's a `null` just before the API URL on the verb section, as you can see on the image below.

<img width="945" alt="Screenshot 2022-11-05 at 23 31 21" src="https://user-images.githubusercontent.com/2768415/200143771-ee56dace-7852-4459-b8be-aebf1360ef03.png">

And here's the project on GitHub, in case you want to reproduce the issue https://github.com/wlsf82/cy-api-coursify.

**Note:** Look for the [`cypress-plugin-api-v2` branch](https://github.com/wlsf82/cy-api-coursify/tree/cypress-plugin-api-v2).

Cc @filiphric.

**Comment by filiphric** [comment]
great catch, thanks for reporting! I’ll fix it right away!
