### ISSUE TITLE
size NaN undefined 

### ISSUE THREAD

**Issue by lucasdonato** [filiphric/cypress-plugin-api#43]
Hi Filip, 

* in version 2.1.1 of cypress-plugin-api the Size field is returning NaN undefined
* some blank margins are being displayed in the layout

![image](https://user-images.githubusercontent.com/12953400/200145506-c8317997-5936-4a34-9f57-4dacf5206019.png)

**Comment by filiphric** [comment]
Thanks for the report 👍 the aize is counted from `content-length` header which I assumed is part of every response. I guess it's not so I'll add a method to count the size manually.

**Comment by filiphric** [comment]
Btw I think those blank spaces are windows scrollbars. I'll find a way of getting ris of them too

**Comment by filiphric** [comment]
@lucasdonato Just released version. As a part of the release, I tried to fix the scrollbar issue, could you confirm that they are gone?

**Comment by lucasdonato** [comment]
It worked perfectly, thanks!
