### ISSUE TITLE
Add response time, headers and size to view

### ISSUE THREAD

**Issue by filiphric** [filiphric/cypress-plugin-api#5]
It’s not there yet, but it’s useful info, so it needs to be added.

**Comment by dodosaurus** [comment]
+1

For headers (request/response) - it would be maybe nice to have some expandable component (option to show/hide the headers), to have the view cleaner.

**Comment by filiphric** [comment]
thought about that, but there needs to be a smart way of doing this, because while you could nicely switch on the last test, you would have quite the trouble doing this with timeline snapshots. it’s the same problem as with #1

**Comment by filiphric** [comment]
will be released in v2
