### ISSUE TITLE
After Merage with Last request and Before Request not Before not showing

### ISSUE THREAD

**Issue by matifniaz** [filiphric/cypress-plugin-api#52]
**After the Request merges with last API Request** and Before Request not showing.
**Verison latest V[2.3.1]**(https://www.npmjs.com/package/cypress-plugin-api/v/2.3.1)
The snapshot is attached for reference.
![12121212](https://user-images.githubusercontent.com/40147842/200329364-32fdd0e0-1678-4ebb-b027-b0b11ede43ea.png)
![image](https://user-images.githubusercontent.com/40147842/200329471-fd65b4c9-9f0a-441f-8173-fb4a5fa14696.png)

**Comment by filiphric** [comment]
Hey @matifniaz I don’t think I follow. What exactly is not showing on the snapshot that should be there?

**Comment by matifniaz** [comment]
Two issues:

1. In **before** have **login** API that is not showing.
2. **After** merge with my last API "emailTemplateList"

![12121212](https://user-images.githubusercontent.com/40147842/200335267-0e8dd298-423e-40c9-a60f-16f6155db09d.png)

**Comment by filiphric** [comment]
So do I understand correctly that the scrolling does not work here? What OS & browser is this please?

**Comment by matifniaz** [comment]
**OS - Windows 11 Browser Chrome**

Not a scrolling issue. **Before** not showing and **After** the payload request response merges with the last API request.

**Comment by filiphric** [comment]
oooooooh I think I understand now. I’ll take a look and make sure to fix this

**Comment by filiphric** [comment]
oooooooh I think I understand now. I’ll take a look and make sure to fix this

**Comment by filiphric** [comment]
hey @matifniaz can you please send a reproducible issue? I cannot seem to replicate this. before and after hooks work well, I don’t see any merging of payloads.

**Comment by matifniaz** [comment]
@filiphric  - Thanks for helping us and sorry for the late response.
Please see the below code and snapshot, In the last when I click on the "After All" Request its showing the result with the last API Request/Response.
`/// <reference types="Cypress" />
const url = 'https://reqres.in';
describe("API TestCases",()=>{
    before(()=>{
            cy.api('GET', url + '/api/users?page=2')
                .then((response) => {
                    expect(response).to.have.property('status', 200)
                    expect(response.body.data[0].email).to.equal('michael.lawson@reqres.in')
                })
    })

    after(()=>{
            cy.api('GET', url + '/api/users/2')
                .then((response) => {
                    expect(response).to.have.property('status', 200)
                    expect(response.body.data.email).to.equal('janet.weaver@reqres.in')
                })
    })
it('POST --> CREATE', () => {
    cy.api({
        'method': 'POST',
        'url': url + '/api/users',
        headers: {
            'Content-Type': 'application/json'
        },
        body: {
            "name": "AtifNiaz",
            "job": "Lead SQA"
        }

    })
        .then((response) => {
            expect(response).to.have.property('status', 201)
            expect(response.body.name).to.equal('AtifNiaz')
            expect(response.body.job).to.equal('Lead SQA')
            expect(response.body.id).not.to.be.null
            expect(response.body.createdAt).not.to.be.null
        })
})
it('PUT --> UPDATE', () => {
    cy.api({
        'method': 'PUT',
        'url': url + '/api/users/2',
        headers: {
            'Content-Type': 'application/json'
        },
        body: {
            "name": "AtifNiaz",
            "job": "Lead SQA"
        }
    })
        .then((response) => {
            expect(response).to.have.property('status', 200)
            expect(response.body.name).to.equal('AtifNiaz')
            expect(response.body.job).to.equal('Lead SQA')
            expect(response.body.createdAt).not.to.be.null
        })
})
})
`
![image](https://user-images.githubusercontent.com/40147842/201670353-5a350048-939a-43a0-bad5-5ec143eee5c5.png)

**Comment by filiphric** [comment]
this is how Cypress works, there’s not too much I can do with that. you will see the api call from `before()` hook as part of your first test and api call from `after()` hook in your last test.
