### ISSUE TITLE
hideCredentials: true is not working.

### ISSUE THREAD

**Issue by matifniaz** [filiphric/cypress-plugin-api#54]
**hideCredentials: true** is not working.
Version - [2.3.1](https://www.npmjs.com/package/cypress-plugin-api/v/2.3.1)
OS: Windows 11
Browser: chrome.
Snapshot is attached for reference.
![image](https://user-images.githubusercontent.com/40147842/200501743-8a967a98-4670-4783-985d-db3f1a4aa82b.png)

![image](https://user-images.githubusercontent.com/40147842/200501958-e2e00841-f8e7-4bef-9c32-ce8046092754.png)
Clear Username and Password showing on UI, Snapshot attached for reference.
![image](https://user-images.githubusercontent.com/40147842/200502206-0a5d7779-59b5-40fe-9fa0-480299498c15.png)

**Comment by filiphric** [comment]
Hey @matifniaz the feature itself is working, but it is not covering attributes `username` or `password`. I’ll add this to the bunch with next release.
