### ISSUE TITLE
[Request] Scrolling to Payload

### ISSUE THREAD

**Issue by burakkaygusuz** [filiphric/cypress-plugin-api#58]
Hi Filip! Is it possible the scrolling to related request/response body payload which is right panel, when the clicking to the request endpoint in command log? Thanks.

**Comment by filiphric** [comment]
Can you please specify what you mean? By default, the plugin should scroll down to last request. On snapshot view, you should be able to see the last request that was made during the snapshot. If not, you should be able to scroll to it

**Comment by burakkaygusuz** [comment]
When I click on the request I want to monitor, the right panel should scroll up or scroll down to focus on the related payload. If a test includes multiple requests and it doesn't fit on the viewport, I'm having trouble finding the payload I want to monitor. Is it clear enough for you?

![Screenshot 2022-11-11 160800](https://user-images.githubusercontent.com/17873574/201346918-45acdee3-47b0-4d53-b058-3e5cd9c84f44.png)

**Comment by filiphric** [comment]
Hey @burakkaygusuz thanks. I’ve been able to replicate it. I don’t yet have a solution for this, but I’m thinking that maybe I could create a snapshot that would highlight the APi request in the UI
