### ISSUE TITLE
[Bug] Invalidation of Printed Information

### ISSUE THREAD

**Issue by burakkaygusuz** [filiphric/cypress-plugin-api#59]
Hi Filip! We use this plugin with [cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) together in our project. There are of course multiple scenarios in our feature files. But the printed information of requests belongs to previous scenarios have been overriding until the last scenario executes. Well, only requests for the last scenario has can be viewed. Do you have any solution for this? Thanks.

Cypress version: 11.0.1
Preproccessor version: 14.0.0
Plugin version: 2.3.3

```
e2e: {
    setupNodeEvents,
    snapshotOnly: true,
    excludeSpecPattern: '*.js',
    specPattern: '**/*.feature',
    experimentalSessionAndOrigin: true,
    experimentalWebKitSupport: true,
    experimentalInteractiveRunEvents: true,
    requestMode: true,
  }
```

**Comment by filiphric** [comment]
Hey @burakkaygusuz ! I don't use cucumber preprocessor at all, can't say I'm a bug fan of it. But I could take a look into the issue if you can provide me with a repo with a reproducible example.
