### ISSUE TITLE
timeout inside cy.request don't work

### ISSUE THREAD

**Issue by diegoscastanho** [filiphric/cypress-plugin-api#66]
Hi, when I try to use the cy.request() timeout I get the following: 
```
cy.request({
        method: 'GET',
        timeout: 30000,  // 30s
        url: Cypress.env('BASE_API_URL') + endpoint,
        headers: {
            authorization: authorization,
        },
        failOnStatusCode: false
});
```
Wait only 4 seconds

![image](https://user-images.githubusercontent.com/64171436/201943073-b4643d6f-c445-4d49-8203-7bf37bb023e4.png)

    Could you please take a look at it? Thanks!

**Comment by filiphric** [comment]
Hey thanks for the report! Fix is going out now, will be released in couple of minutes
