### ISSUE TITLE
Ran into TypeError when cy.api() call was made from global hooks

### ISSUE THREAD

**Issue by kunalashar25** [filiphric/cypress-plugin-api#67]
Hi,

I'm having the following file structure
```
.
└── project/
    └── cypress/
        ├── e2e/
        │   └── *.cy.ts
        └── support/
            ├── e2e.js
            └── hooks.js
```

`hooks.js` contains global hooks. Example:

```
after('remove automation data', () => {
    removeAutomationData();
});
```

`e2e.js` contains
```
import './hooks';
import 'cypress-plugin-api';
```

When functions `removeAutomationData()` internally makes `cy.api()` request. I'm seeing the following error:
```
TypeError: Cannot read properties of undefined (reading 'Reproducing global hooks issue.should throw error for global hooks')
Because this error occurred during a `after all` hook we are skipping all of the remaining tests.
    at Context.eval (webpack:///./node_modules/cypress-plugin-api/dist/support.js:3:10683)
```
<img width="1552" alt="Screenshot 2022-11-18 at 7 56 54 AM" src="https://user-images.githubusercontent.com/28864358/202585360-89ce64e3-56ff-4f1f-bdbb-e2d5fab828ca.png">

**Note:** If hooks are present directly inside `*.cy.ts` files then there is no issue in execution.

**Comment by filiphric** [comment]
Interesting. Can you share what is inside the `removeAutomationData()` function? The error seems to be pointing to a `.should()` assertion that trying to access an object attribute, but cannot find it. from the looks of it it seems like some kind of missing reference, but it’s hard to tell honestly

**Comment by kunalashar25** [comment]
@filiphric I tried again it seems to be working today, not sure why I ran into an error before. Can mark this as closed for now.
