### ISSUE TITLE
feat: expose api function

### ISSUE THREAD

**Issue by jordanpowell88** [filiphric/cypress-plugin-api#95]
I was just working on implementing this but I needed  a way to wrap the `cy.api()`. It would be great if I could easily do something like this in my support file:

```typescript
import { api } from 'cypress-plugin-api'

declare global {
  namespace Cypress {
    interface Chainable {
      api: typeof api
    }
  }
}

Cypress.Commands.add('api', myCustomMount)
```

**Comment by filiphric** [comment]
Great idea, thanks for this 👍  Releasing in 2.8.0
