### ISSUE TITLE
{ forceNetworkError: true } being presented in the url context

### ISSUE THREAD

**Issue by guilhermesousa-cwi** [filiphric/cypress-plugin-api#99]
I have a doubt if this is a problem or not.

✅ This scenario returned status code 500 as expected. The lib concatenated the URL + { force network error: true }.
![image](https://user-images.githubusercontent.com/118919569/209555063-c44fbf52-5732-4937-8e4c-025b475c78f2.png)

❌ This scenario returned status code 404 (expected 500). The lib concatenated the URL + { force network error: true }.
![image](https://user-images.githubusercontent.com/118919569/209555077-5c6811ed-588a-4215-99fb-e3cf8ab70146.png)

**PS**: The difference between the two requests is that one passes at the end of the url ${posIdCnpjNull} and the other /customers with the name of the endpoint (/customers).

--------------------------------------------------------------------------------------------------------------------------------------

**Version:**
"cypress": "^11.2.0"
"cypress-plugin-api": "^2.6.1"

**Comment by filiphric** [comment]
this is not really a provblem od the plugin. you are not setting up the parameter correctly. also, there’s no `forceNetworkError` parameter in `cy.request()`, see [Cypress docs](https://docs.cypress.io/api/commands/request#Arguments)
